package organotiki.mobile.mobilestreet.objects;

import java.util.Date;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

/**
 * Created by Thanasis on 25/5/2016.
 */
public class GlobalVar extends RealmObject {

    @PrimaryKey
    private String ID;
    private String LocalIP;
    private String OnlineIP;
    private User myUser;
    private CompanySite myCompanySite;
    private Invoice myInvoice;
    private FInvoice myFInvoice;
    private String LastUpdate;
    private String VerNum;
    private String ErrorItem;
    private String ErrorAlternateCode;
    // Standard getters & setters generated by your IDE…

    public GlobalVar() {
    }

    public GlobalVar(String ID, String localIP, String onlineIP, String lastUpdate, String verNum,String errorItem,String errorAlternateCode) {
        this.ID = ID;
        LocalIP = localIP;
        OnlineIP = onlineIP;
        LastUpdate = lastUpdate;
        VerNum = verNum;
        ErrorItem=errorItem;
        ErrorAlternateCode=errorAlternateCode;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public String getOnlineIP() {
        return OnlineIP;
    }

    public void setOnlineIP(String onlineIP) {
        OnlineIP = onlineIP;
    }

    public User getMyUser() {
        return myUser;
    }

    public void setMyUser(User myUser) {
        this.myUser = myUser;
    }

    public Invoice getMyInvoice() {
        return myInvoice;
    }

    public void setMyInvoice(Invoice myInvoice) {
        this.myInvoice = myInvoice;
    }

    public FInvoice getMyFInvoice() {
        return myFInvoice;
    }

    public void setMyFInvoice(FInvoice myFInvoice) {
        this.myFInvoice = myFInvoice;
    }

    public String getVerNum() {
        return VerNum;
    }

    public void setVerNum(String verNum) {
        VerNum = verNum;
    }

    public CompanySite getMyCompanySite() {
        return myCompanySite;
    }

    public void setMyCompanySite(CompanySite myCompanySite) {
        this.myCompanySite = myCompanySite;
    }

    public void refresh(){
//        myCompanySite = null;
        myFInvoice = null;
        myInvoice = null;
        myUser = null;
    }

    public String getLocalIP() {
        return LocalIP;
    }

    public void setLocalIP(String localIP) {
        LocalIP = localIP;
    }

    public String getLastUpdate() {
        return LastUpdate;
    }

    public void setLastUpdate(String lastUpdate) {
        LastUpdate = lastUpdate;
    }

    public String getErrorItem() {
        return ErrorItem;
    }

    public void setErrorItem(String errorItem) {
        ErrorItem = errorItem;
    }

    public String getErrorAlternateCode() {
        return ErrorAlternateCode;
    }

    public void setErrorAlternateCode(String errorAlternateCode) {
        ErrorAlternateCode = errorAlternateCode;
    }
}
